env:
  browser: true
  commonjs: true
  es6: true
extends:
  - google
  - plugin:vue/essential
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  {
    max-len: 0,
    require-jsdoc: 0,
    new-cap: 0,
    prefer-promise-reject-errors: 0,
    guard-for-in: 0,
    no-unused-vars: 1,
    vue/no-use-v-if-with-v-for: 1
  }
