name: Sync Fork

on:
  #push:
    #branches:
     # - master
  workflow_dispatch: # on button click
  schedule:
    - cron: '0 14 * * *'

#permissions:
 # contents: write

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: userXinos
          base: master
          head: master
          merge_method: rebase
