name: Sync Fork

env:
  tz: Asia/Shanghai

on:
  #push:
    #branches:
     # - master
  workflow_dispatch: # on button click
  schedule:
    - cron: '0 0 */3 * *'   # 每3天的凌晨0点

#permissions:
 # contents: write

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: userXinos
          base: master
          head: master
          merge_method: rebase
