name: Auto Merge
on: pull_request_target
permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    if: github.actor == 'github-actions[bot]'  
    runs-on: ubuntu-latest
    steps:
      - name: 批准PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })

      - name: 启用自动合并
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge  # 可选 squash/rebase