name: Web app deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Dependencies
        run: |
          yarn global add @vue/cli-service-global

      - name: Generate game data
        working-directory: ./generateGameData
        run: |
          npm install
          npm run generateFrontendData

      - name: Build
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./frontend/dist
