name: Deploy

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          yarn global add @vue/cli-service-global
          npm run install-prod

      - name: Build
        run: |
          npm run build

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: dist
          git-config-name: "GitHub Actions"
          git-config-email: "actions@github.com"
